stages:
  - build
  - deploy

build_prod:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  only:
    - main

deploy_prod:
  stage: deploy
  image:
    name: docker:dind
  variables:
    DOCKER_HOST: "ssh://root@$DROPLET_IP"
  before_script:
    - apk update && apk add openssh-client bash
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker container stop $CONTAINER_NAME
    - docker container rm $CONTAINER_NAME
    - > 
      docker container run -d 
      --name $CONTAINER_NAME 
      -e OPENAI_API_KEY=$OPEN_API_KEY
      -e TOKEN=$TOKEN
      $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  only:
    - main
