export const GANDONE_STICKER = 'CAACAgIAAxkBAAEKZHplElHPX99-Qj3MTS3r0O2cule--gACCiYAArkQaEksYoQTtEf5LTAE';
export const PHOTO_CLOWN = 'CAACAgIAAxkBAAEKZLBlEo0-GulfMbwhRgEW7is2Nxc23gACcCgAAkiP6UkBU4BvBnBFWDAE';
